const state = { category: "all", use: "all", query: "", recent: false, sort: "newest" };
const categoryMap = Object.fromEntries(CATEGORIES.map((category) => [category.id, category]));
const latestAdded = new Date(Math.max(...TOOLS.map((tool) => new Date(`${tool.added || tool.verified}T00:00:00`))));
const recentCutoff = new Date(latestAdded); recentCutoff.setDate(recentCutoff.getDate() - 2);
const isRecent = (tool) => new Date(`${tool.added || tool.verified}T00:00:00`) >= recentCutoff;
const recentTools = TOOLS.filter(isRecent);
const $ = (selector) => document.querySelector(selector);
const els = { categoryNav: $("#categoryNav"), categoryStats: $("#categoryStats"), toolGrid: $("#toolGrid"), updateDays: $("#updateDays"), search: $("#searchInput"), mobileSearch: $("#mobileSearchInput"), useFilter: $("#useFilter"), sortFilter: $("#sortFilter"), recentFilter: $("#recentFilter"), resultCount: $("#resultCount"), activeFilterLabel: $("#activeFilterLabel"), empty: $("#emptyState"), dialog: $("#toolDialog"), dialogContent: $("#dialogContent") };

function escapeHtml(value) { return String(value).replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]); }
function formatDate(date, full = false) { return new Date(`${date}T00:00:00`).toLocaleDateString("he-IL", full ? { weekday: "long", day: "numeric", month: "long" } : { day: "numeric", month: "numeric", year: "numeric" }); }
function logoMarkup(tool, large = false) { const host = new URL(tool.url).hostname; return `<span class="tool-logo ${large ? "large" : ""}" style="--category:${categoryMap[tool.category].color}"><span>${escapeHtml(tool.mark)}</span><img src="https://www.google.com/s2/favicons?sz=128&domain_url=${encodeURIComponent(host)}" alt="" loading="lazy" onerror="this.hidden=true" /></span>`; }
function compactFree(text) { const first = text.split(".")[0]; return first.length > 112 ? `${first.slice(0, 109)}…` : `${first}.`; }
function toolCard(tool) { const category = categoryMap[tool.category]; return `<article class="tool-card" data-tool="${tool.slug}" tabindex="0" role="button" aria-label="פרטים על ${escapeHtml(tool.name)}" style="--category:${category.color}"><div class="card-head">${logoMarkup(tool)}<div class="card-meta"><span>${category.short}</span>${isRecent(tool) ? `<time datetime="${tool.added}">חדש · ${formatDate(tool.added)}</time>` : `<span>אומת ${formatDate(tool.verified)}</span>`}</div><span class="card-arrow" aria-hidden="true">↙</span></div><h3>${escapeHtml(tool.name)}</h3><p class="card-tagline">${escapeHtml(tool.tagline)}</p><div class="tag-row">${tool.subcategories.slice(0, 2).map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</div><p class="free-summary"><strong>מה חינם</strong>${escapeHtml(compactFree(tool.free))}</p></article>`; }
function updateItem(tool) { return `<button type="button" class="update-item" data-tool="${tool.slug}" style="--category:${categoryMap[tool.category].color}">${logoMarkup(tool)}<span><strong>${escapeHtml(tool.name)}</strong><small>${escapeHtml(tool.tagline)}</small></span><i>${categoryMap[tool.category].short}</i></button>`; }
function renderNavigation() { els.categoryNav.innerHTML = CATEGORIES.map((category) => { const count = category.id === "all" ? TOOLS.length : TOOLS.filter((tool) => tool.category === category.id).length; return `<button type="button" data-category="${category.id}" class="${state.category === category.id ? "active" : ""}" style="--category:${category.color || "#111510"}"><i></i><span>${escapeHtml(category.short)}</span><strong>${count}</strong></button>`; }).join(""); }
function renderStats() { els.categoryStats.innerHTML = CATEGORIES.slice(1).map((category) => { const count = TOOLS.filter((tool) => tool.category === category.id).length; return `<button type="button" data-category="${category.id}" style="--category:${category.color}"><i></i><span>${category.name}</span><strong>${count}</strong><small>כלים</small></button>`; }).join(""); }
function renderUpdates() { const groups = [...new Set(recentTools.map((tool) => tool.added))].sort().reverse(); els.updateDays.innerHTML = groups.map((date) => { const items = recentTools.filter((tool) => tool.added === date); return `<section class="update-day"><header><time datetime="${date}">${formatDate(date, true)}</time><span>${items.length} כלים</span></header><div>${items.map(updateItem).join("")}</div></section>`; }).join(""); }
function renderUseOptions() { const uses = [...new Set(TOOLS.flatMap((tool) => tool.uses))].sort((a, b) => a.localeCompare(b, "he")); els.useFilter.insertAdjacentHTML("beforeend", uses.map((use) => `<option value="${escapeHtml(use)}">${escapeHtml(use)}</option>`).join("")); }
function filteredTools() { const query = state.query.trim().toLocaleLowerCase("he"); const tools = TOOLS.filter((tool) => { const searchable = [tool.name, tool.tagline, tool.solves, tool.free, tool.limits, ...tool.uses, ...tool.subcategories].join(" ").toLocaleLowerCase("he"); return (state.category === "all" || tool.category === state.category) && (state.use === "all" || tool.uses.includes(state.use)) && (!state.recent || isRecent(tool)) && (!query || searchable.includes(query)); }); return tools.sort((a, b) => state.sort === "name" ? a.name.localeCompare(b.name) : state.sort === "category" ? a.category.localeCompare(b.category) || a.name.localeCompare(b.name) : (b.added || b.verified).localeCompare(a.added || a.verified) || a.name.localeCompare(b.name)); }
function renderCatalog() { const tools = filteredTools(); els.toolGrid.innerHTML = tools.map(toolCard).join(""); els.resultCount.textContent = `${tools.length} מתוך ${TOOLS.length}`; els.activeFilterLabel.textContent = state.category === "all" ? "כל הקטגוריות" : categoryMap[state.category].name; els.empty.hidden = tools.length !== 0; els.toolGrid.hidden = tools.length === 0; renderNavigation(); }

function detailTemplate(tool) { const category = categoryMap[tool.category]; const list = (items) => items.map((item) => `<li>${escapeHtml(item)}</li>`).join(""); return `<header class="dialog-header" style="--category:${category.color}">${logoMarkup(tool, true)}<div><p>${category.name}</p><h2 id="dialogTitle">${escapeHtml(tool.name)}</h2><p>${escapeHtml(tool.tagline)}</p></div></header><div class="dialog-body"><section><p class="detail-label">מה הכלי עושה</p><h3>${escapeHtml(tool.solves)}</h3><p><strong>למי מתאים:</strong> ${escapeHtml(tool.audience)}</p></section><section class="free-panel"><p class="detail-label">המסלול החינמי</p><h3>${escapeHtml(tool.free)}</h3><p><strong>המגבלה שחשוב להכיר:</strong> ${escapeHtml(tool.limits)}</p></section><div class="pros-cons"><section><p class="detail-label">יתרונות</p><ul>${list(tool.pros)}</ul></section><section><p class="detail-label">חסרונות</p><ul>${list(tool.cons)}</ul></section></div><section><p class="detail-label">חלופות</p><div class="chip-list">${tool.alternatives.map((name) => `<button type="button" data-alternative="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join("")}</div></section><section><p class="detail-label">אימות ומקורות</p><p>נוסף לקטלוג: ${formatDate(tool.added || tool.verified)} · אומת לאחרונה: ${formatDate(tool.verified)}</p><div class="source-list">${tool.sources.map((source) => `<a href="${source.url}" target="_blank" rel="noreferrer">${escapeHtml(source.label)} ↗</a>`).join("")}</div></section></div><div class="dialog-actions"><a href="${tool.url}" target="_blank" rel="noreferrer">מעבר לאתר הרשמי <span>↗</span></a></div>`; }
function openTool(slug, updateHash = true) { const tool = TOOLS.find((item) => item.slug === slug); if (!tool) return; els.dialogContent.innerHTML = detailTemplate(tool); if (!els.dialog.open) els.dialog.showModal(); if (updateHash) history.pushState(null, "", `#tool=${tool.slug}`); }
function closeDialog(updateHash = true) { if (els.dialog.open) els.dialog.close(); if (updateHash && location.hash.startsWith("#tool=")) history.pushState(null, "", location.pathname + location.search); }
function resetFilters() { state.category = "all"; state.use = "all"; state.query = ""; state.recent = false; state.sort = "newest"; [els.search, els.mobileSearch].forEach((input) => input.value = ""); els.useFilter.value = "all"; els.sortFilter.value = "newest"; els.recentFilter.checked = false; renderCatalog(); }
function syncSearch(value, source) { state.query = value; (source === els.search ? els.mobileSearch : els.search).value = value; renderCatalog(); }

document.addEventListener("click", (event) => { const tool = event.target.closest("[data-tool]"); const category = event.target.closest("[data-category]"); const view = event.target.closest("[data-view]"); const alternative = event.target.closest("[data-alternative]"); if (tool) openTool(tool.dataset.tool); if (category) { state.category = category.dataset.category; renderCatalog(); $("#catalog").scrollIntoView({ behavior: "smooth" }); } if (view) $(`#${view.dataset.view}`).scrollIntoView({ behavior: "smooth" }); if (alternative) { const match = TOOLS.find((item) => item.name === alternative.dataset.alternative); if (match) openTool(match.slug); } if (event.target.closest("[data-clear]")) resetFilters(); });
document.addEventListener("keydown", (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); (innerWidth <= 760 ? els.mobileSearch : els.search).focus(); } if ((event.key === "Enter" || event.key === " ") && event.target.matches(".tool-card")) { event.preventDefault(); openTool(event.target.dataset.tool); } });
els.search.addEventListener("input", () => syncSearch(els.search.value, els.search)); els.mobileSearch.addEventListener("input", () => syncSearch(els.mobileSearch.value, els.mobileSearch)); els.useFilter.addEventListener("change", () => { state.use = els.useFilter.value; renderCatalog(); }); els.sortFilter.addEventListener("change", () => { state.sort = els.sortFilter.value; renderCatalog(); }); els.recentFilter.addEventListener("change", () => { state.recent = els.recentFilter.checked; renderCatalog(); });
$("#filterRecent").addEventListener("click", () => { state.recent = true; els.recentFilter.checked = true; renderCatalog(); $("#catalog").scrollIntoView({ behavior: "smooth" }); }); $("#clearFilters").addEventListener("click", resetFilters); $("#closeDialog").addEventListener("click", () => closeDialog()); els.dialog.addEventListener("click", (event) => { if (event.target === els.dialog) closeDialog(); }); els.dialog.addEventListener("cancel", (event) => { event.preventDefault(); closeDialog(); }); window.addEventListener("hashchange", () => { const slug = location.hash.match(/^#tool=(.+)$/)?.[1]; slug ? openTool(slug, false) : closeDialog(false); });
renderUseOptions(); renderStats(); renderUpdates(); renderCatalog(); $("#heroTotal").textContent = TOOLS.length; $("#sidebarTotal").textContent = TOOLS.length; $("#recentCount").textContent = recentTools.length; const initialSlug = location.hash.match(/^#tool=(.+)$/)?.[1]; if (initialSlug) openTool(initialSlug, false);
